"""Foundational types and constants shared across the package, with no internal dependencies."""

from .types import (
    # Singular aliases
    Stream,
    String,
    Scalar,
    Real,
    Time,
    Atom,
    Vec,
    Map,
    Iter,
    Struct,
    Func,
    Object,
    Model,
    Dataclass,
    # Generic (parametrizable) aliases
    _Vec,
    _Map,
    _Iter,
    _Struct,
    _Func,
    # Tuple collections (isinstance-safe)
    Streams,
    Strings,
    Scalars,
    Reals,
    Times,
    Enums,
    Atoms,
    Vecs,
    Maps,
    Models,
    Structs,
    Funcs,
    Iters,
    Objects,
    TYPESET,
)
from .constants import INFRA_PATHS, InfraPaths, DELIM, JINJA, get_template

__all__ = [
    'Stream',
    'String',
    'Scalar',
    'Real',
    'Time',
    'Atom',
    'Vec',
    'Map',
    'Iter',
    'Struct',
    'Func',
    'Object',
    'Model',
    'Dataclass',
    '_Vec',
    '_Map',
    '_Iter',
    '_Struct',
    '_Func',
    'Streams',
    'Strings',
    'Scalars',
    'Reals',
    'Times',
    'Enums',
    'Atoms',
    'Vecs',
    'Maps',
    'Models',
    'Structs',
    'Funcs',
    'Iters',
    'Objects',
    'TYPESET',
    'INFRA_PATHS',
    'InfraPaths',
    'DELIM',
    'JINJA',
    'get_template',
]
