# Guided overall by https://docs.astral.sh/uv/guides/integration/gitlab/
######################
### CONTROL BLOCKS ###
######################
include:
    - template: Security/Secret-Detection.gitlab-ci.yml

variables:
    SECRET_DETECTION_ENABLED: 'true'

stages:
    # - build
    - test
    - secret-detection

###################
### UV TEMPLATE ###
###################
.uv:
    # From https://docs.astral.sh/uv/guides/integration/docker/#available-images
    image: ghcr.io/astral-sh/uv:python3.13-trixie-slim

    variables:
        UV_LINK_MODE: copy
        UV_CACHE_DIR: .uv-cache

    # See https://docs.gitlab.com/ci/yaml/#cachekeyfiles
    cache:
        - key: {files: [uv.lock]}
          paths: ["${UV_CACHE_DIR}"]

    before_script:
        - uv sync

    after_script:
        - uv cache prune --ci

#################
### TEST JOBS ###
#################
pytest:
    extends: .uv
    stage: test
    script:
        - uv run pytest

##################
### OTHER JOBS ###
##################
secret_detection:
    stage: secret-detection

