# Guided overall by https://docs.astral.sh/uv/guides/integration/gitlab/
############
### HEAD ###
############
stages:
  - build
  - eval
  - test
  - release

# Import static analysis tools
include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - component: gitlab.com/gitlab-org/professional-services-automation/tools/utilities/pipeintel/pipeintel@1.0.0
    inputs:
      stage: eval
      offline: true

# Determine when this pipeline should run
workflow:
  rules:
    - if: '$CI_COMMIT_TITLE =~ /-draft$/ || $CI_MERGE_REQUEST_DRAFT == "true"'
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

############
### DATA ###
############
variables:
  PACKAGE: my
  DOCKER_TLS_CERTDIR: /certs
  TEST_POD: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  MAIN_POD: $CI_REGISTRY_IMAGE:latest
  SECRET_DETECTION_ENABLED: 'true'

############
### BODY ###
############
default:
  image: ghcr.io/astral-sh/uv:python3.13-bookworm
  before_script:
    - cd $CI_PROJECT_DIR
    - uv sync --all-extras

.docker:
  image: docker:26
  services: [docker:26-dind]
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin

Rebuild Pod:
  stage: build
  extends: .docker
  script:
    - docker build --pull -t $TEST_POD -f Containerfile .
    - docker push $TEST_POD
  rules:
    - changes:
        - Containerfile
        - Taskfile.dist.yaml
        - .repo.yaml

Release Pod:
  stage: release
  extends: .docker
  script:
    - docker pull $TEST_POD
    - docker tag $TEST_POD $MAIN_POD
    - docker push $MAIN_POD
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - changes:
        - Containerfile
        - Taskfile.dist.yaml
        - .repo.yaml

secret_detection:
  stage: eval

Evaluate Python:
  stage: eval
  interruptible: true
  script:
    - uv run ruff check --output-format=gitlab --output-file=code-quality-report.json
    - uv run ruff format --diff
    - uv run pyrefly check
  artifacts:
    reports:
      codequality: $CI_PROJECT_DIR/code-quality-report.json

Test Python:
  stage: test
  script:
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
    - uv run task test:cov
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
