# Guided overall by https://docs.astral.sh/uv/guides/integration/gitlab/
#########################
### I. CONTROL BLOCKS ###
#########################
variables:
    IMAGE: $CI_REGISTRY_IMAGE:latest
    SECRET_DETECTION_ENABLED: 'true'

include:
    - component: gitlab.com/gitlab-org/professional-services-automation/tools/utilities/pipeintel/pipeintel@main
      inputs:
        stage: eval
    - template: Security/Secret-Detection.gitlab-ci.yml

# ---- Lifecyle ----
# These will be executed in turn, corresponding to one or more jobs below
stages:
    - build
    - test
    - eval

# Only run the pipeline for non-draft commits in a Merge Request or directly onto the main branch.
workflow:
    rules:
        - if: '$CI_COMMIT_TITLE =~ /-draft$/ || $CI_MERGE_REQUEST_DRAFT == "true"'
          when: never
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

####################
### II. TEMPLATE ###
####################
default:
    image: $CI_REGISTRY_IMAGE:latest
    cache:
        - key: {files: [uv.lock]}
          paths: ["${UV_CACHE_DIR}"]

#################
### III. JOBS ###
#################
pytest:
    stage: test
    script:
        - task test:cov
    coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

eval:
    # Run semantic linters on source code
    stage: eval
    script:
        - task eval

secret_detection:
    stage: eval
