# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

env:
    FORCE_COLOR: 1

vars:
    SRC_DIR: ./my
    DOC_DIR: ./docs
    RST_DIR: '{{.DOC_DIR}}/_source'
    OUT_DIR: '{{.DOC_DIR}}/_build'

dotenv: [.env, ~/tmp/.env]

tasks:
    # ------
    # PyTest
    # ------
    test: uv run pytest {{.CLI_ARGS}}

    test-dev: uv run pytest --sw -s --pdb -vv --durations=5 --durations-min=0.005
        {{.CLI_ARGS}}

    test-cov: uv run pytest --cov=my --cov-report=term-missing {{.CLI_ARGS}}

    # ------
    # Sphinx
    # ------
    docs-parse:
        desc: Parse Python source code and generate Sphinx .rst files; configured
            in conf.py.
        # cmd: uv run sphinx-apidoc -o {{.RST_DIR}} {{.SRC_DIR}} --remove-old {{.CLI_ARGS}}
        cmd: uv run sphinx-build {{.DOC_DIR}} {{.OUT_DIR}} --fail-on-warning {{.CLI_ARGS}}
        sources: ['{{.SRC_DIR}}/**/*.py', '{{.DOC_DIR}}/conf.py']
        generates: ['{{.RST_DIR}}/*.rst']

    docs-build:
        desc: Build Sphinx .rst files into publishable .html files.
        cmd: uv run sphinx-build {{.DOC_DIR}} {{.OUT_DIR}} --fail-on-warning {{.CLI_ARGS}}
        sources: ['{{.RST_DIR}}/*.rst', '{{.DOC_DIR}}/**/*.md', '{{.DOC_DIR}}/conf.py']
        generates: ['{{.OUT_DIR}}/*.html']
    docs:
        cmds:
            - task: docs-parse
            - task: docs-build

