# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
    SRC_DIR: ./my
    DOC_DIR: ./docs
    API_DIR: '{{.DOC_DIR}}/_source'
    OUT_DIR: '{{.DOC_DIR}}/_build'

tasks:
    # ------
    # PyTest
    # ------
    test: uv run pytest {{.CLI_ARGS}}

    test:dev: uv run pytest --sw -vv --no-cov {{.CLI_ARGS}}

    test:pdb: uv run pytest -s --pdb --sw -vv --no-cov {{.CLI_ARGS}}

    test:cov: uv run pytest --cov=my --cov-report=term-missing --cov-report=markdown:docs/coverage.md
        {{.CLI_ARGS}}

    # ------
    # Sphinx
    # ------
    docs:
        desc: Extract python docstrings into MyST files, then (re)build the finalized
            HTML files.
        cmd: uv run sphinx-build -c {{DOC_DIR}} --fail-on-warning {{.CLI_ARGS}} {{.API_DIR}}
            {{.OUT_DIR}}
        sources:
            - '{{.SRC_DIR}}/**/*.py'
            - '{{.API_DIR}}/*'
            - '{{.DOC_DIR}}/**/*.md'
            - '{{.DOC_DIR}}/conf.py'
        generates: ['{{.OUT_DIR}}/*.html']

