"""Deterministic intake, validation, and reporting for my-basis adoption."""

from .models import (
    Baseline,
    ChangeProposal,
    EvidenceRef,
    FileEvidence,
    Handoff,
    ImportFact,
    Intake,
    ProblemSpace,
    Proposal,
    ProposalSummary,
    RegexExample,
    RegexPatternFact,
    RegexStoreProposal,
    ReportResult,
    Signal,
    VcsResult,
    Verification,
)
from .proposal import (
    ProposalValidationError,
    intake_sha256,
    load_intake,
    load_proposal,
    proposal_template,
    render_html,
    render_myst,
    render_typst,
    validate_proposal,
    validation_error_text,
)
from .scanner import scan_repository

__all__ = [
    'Baseline',
    'ChangeProposal',
    'EvidenceRef',
    'FileEvidence',
    'Handoff',
    'ImportFact',
    'Intake',
    'ProblemSpace',
    'Proposal',
    'ProposalSummary',
    'ProposalValidationError',
    'RegexExample',
    'RegexPatternFact',
    'RegexStoreProposal',
    'ReportResult',
    'Signal',
    'VcsResult',
    'Verification',
    'intake_sha256',
    'load_intake',
    'load_proposal',
    'proposal_template',
    'render_html',
    'render_myst',
    'render_typst',
    'scan_repository',
    'validate_proposal',
    'validation_error_text',
]
